/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 dna-03.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dna-03-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.wave1.geometry} material={nodes.wave1.material} />
      <mesh geometry={nodes.wave2.geometry} material={nodes.wave2.material} />
    </group>
  )
}

useGLTF.preload('/dna-03-transformed.glb')
